name: twitter_qr_scanner
description: Twitter qr code scan package for flutter.
version: 0.0.6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^3.1.0
  common_utils: ^1.2.1
  flare_flutter: ^1.7.3
  carousel_slider: ^1.3.1
  image_picker: ^0.6.7+14
  image_cropper: ^1.3.1
  flutter_qr_reader: 
    git:
      url: https://github.com/TheArchitect123/flutter_qr_reader.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/twitter_qr_scanner/asset/QRButton.flr

